=== digitalcafe/weblounge/modules/weblounge-common/src/main/resources/xsd/module.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.entwinemedia.com/weblounge/3.0/module" xmlns="http://www.entwinemedia.com/weblounge/3.0/module"
	elementFormDefault="qualified">

  <xsd:element name="module">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="enable" type="xsd:boolean" />
        <xsd:element name="class" type="xsd:string" minOccurs="0" />
        <xsd:element name="name" type="xsd:string" minOccurs="0" />
        <xsd:element ref="pagelets" minOccurs="0" />
        <xsd:element ref="actions" minOccurs="0" />
        <xsd:element ref="jobs" minOccurs="0" />
        <xsd:element ref="imagestyles" minOccurs="0" />
        <xsd:element ref="options" minOccurs="0" />
      </xsd:sequence>
      <xsd:attribute name="id" type="idType" use="required" />
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="pagelets">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="pagelet" minOccurs="0" maxOccurs="unbounded" />
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="pagelet">
  	<xsd:complexType>
  		<xsd:sequence>
        <xsd:element name="name" type="xsd:string" minOccurs="0" />
        <xsd:element name="class" type="xsd:string" minOccurs="0" />
        <xsd:element ref="renderer" minOccurs="1" maxOccurs="unbounded"/>
  			<xsd:element name="editor" type="xsd:anyURI" minOccurs="0" />
  			<xsd:element name="recheck" type="durationType" minOccurs="0" />
  			<xsd:element name="valid" type="durationType" minOccurs="0" />
        <xsd:element ref="preview" minOccurs="0" />
  			<xsd:element ref="includes" minOccurs="0" />
  		</xsd:sequence>
  		<xsd:attribute name="id" type="idType" use="required" />
  		<xsd:attribute name="composeable" type="xsd:boolean" />
  	</xsd:complexType>
  </xsd:element>

  <xsd:element name="renderer">
    <xsd:complexType>
      <xsd:simpleContent>
        <xsd:extension base="xsd:anyURI">
          <xsd:attribute name="type" type="xsd:string" />
        </xsd:extension>
      </xsd:simpleContent>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="preview">
    <xsd:simpleType>
      <xsd:restriction base="xsd:string">
        <xsd:enumeration value="none" />
        <xsd:enumeration value="first" />
        <xsd:enumeration value="all" />
        <xsd:enumeration value="boundary" />
      </xsd:restriction>
    </xsd:simpleType>
  </xsd:element>

  <xsd:element name="actions">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="action" minOccurs="0" maxOccurs="unbounded" />
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="action">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="name" type="xsd:string" minOccurs="0" />
        <xsd:element name="class" type="xsd:string" />
        <xsd:element name="mountpoint" type="xsd:anyURI" />
        <xsd:element name="page" type="xsd:anyURI" minOccurs="0" />
        <xsd:element name="template" type="xsd:string" minOccurs="0" />
        <xsd:element name="recheck" type="xsd:string" minOccurs="0" />
        <xsd:element name="valid" type="xsd:string" minOccurs="0" />
        <xsd:element ref="includes" minOccurs="0" />
        <xsd:element ref="options" minOccurs="0" />
      </xsd:sequence>
      <xsd:attribute name="id" type="idType" use="required" />
      <xsd:attribute name="composeable" type="xsd:boolean" />
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="jobs">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="job" minOccurs="0" maxOccurs="unbounded" />
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="job">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="name" type="xsd:string" minOccurs="0" />
        <xsd:element name="class" type="xsd:string" />
        <xsd:element name="schedule" type="xsd:string" />
        <xsd:element ref="options" minOccurs="0" />
      </xsd:sequence>
      <xsd:attribute name="id" type="idType" use="required" />
    </xsd:complexType>
  </xsd:element>
  
  <xsd:element name="imagestyles">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="imagestyle" minOccurs="0" maxOccurs="unbounded" />
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="imagestyle">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="name" type="xsd:string" minOccurs="0" />
        <xsd:element ref="scalingmode" />
        <xsd:element name="width" type="xsd:int" minOccurs="0" />
        <xsd:element name="height" type="xsd:int" minOccurs="0" />
      </xsd:sequence>
      <xsd:attribute name="id" type="idType" use="required" />
      <xsd:attribute name="composeable" type="xsd:boolean" />
      <xsd:attribute name="preview" type="xsd:boolean" />
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="scalingmode">
    <xsd:simpleType>
      <xsd:restriction base="xsd:string">
        <xsd:enumeration value="width" />
        <xsd:enumeration value="height" />
        <xsd:enumeration value="box" />
        <xsd:enumeration value="fill" />
        <xsd:enumeration value="cover" />
        <xsd:enumeration value="none" />
      </xsd:restriction>
    </xsd:simpleType>
  </xsd:element>
  
  <xsd:element name="includes">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="link" minOccurs="0" maxOccurs="unbounded" />
        <xsd:element ref="script" minOccurs="0" maxOccurs="unbounded" />
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  
  <xsd:element name="link">
    <xsd:complexType>
      <xsd:attribute name="use" type="useType" use="optional" />
      <xsd:attribute name="href" type="xsd:anyURI" use="required" />
      <xsd:attribute name="type" type="xsd:string" use="required" />
      <xsd:attribute name="charset" type="xsd:string" use="optional" />
      <xsd:attribute name="media" type="xsd:string" use="optional" />
      <xsd:attribute name="rel" type="xsd:string" use="optional" />
      <xsd:attribute name="rev" type="xsd:string" use="optional" />
    </xsd:complexType>
  </xsd:element>
  
  <xsd:element name="script">
    <xsd:complexType>
      <xsd:attribute name="jquery" type="xsd:string" use="optional" />
      <xsd:attribute name="use" type="useType" use="optional" />
      <xsd:attribute name="src" type="xsd:anyURI" use="required" />
      <xsd:attribute name="type" type="xsd:string" use="required" />
      <xsd:attribute name="charset" type="xsd:string" use="optional" />
      <xsd:attribute name="defer" type="xsd:boolean" use="optional" />
    </xsd:complexType>
  </xsd:element>
  
  <xsd:element name="options">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="option" maxOccurs="unbounded" />
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

  <!--
  Options are defined by a name and either a single value or a list of values.
  Multiple values are put into a value element each.
  -->
  <xsd:element name="option">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="name" type="xsd:string" minOccurs="1" maxOccurs="1" />
        <xsd:element name="value" type="optionValueType" minOccurs="1" maxOccurs="unbounded" />
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  
  <xsd:complexType name="optionValueType">
    <xsd:simpleContent>
      <xsd:extension base="xsd:string">
        <xsd:attribute name="environment" type="environmentType" />
      </xsd:extension>
    </xsd:simpleContent>
  </xsd:complexType>
  
  <xsd:simpleType name="environmentType">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="production" />
      <xsd:enumeration value="staging" />
      <xsd:enumeration value="development" />
    </xsd:restriction>
  </xsd:simpleType>
  
  <!-- 
  Type definition for identifiers. Since identifiers are used in path names
  and potentially database table and column names as well, they are restricted
  to contain commonly unproblematic characters only.
   -->
  <xsd:simpleType name="idType">
    <xsd:restriction base="xsd:ID">
      <xsd:pattern value="[a-zA-Z0-9]+[a-zA-Z0-9\-_.]*" />
    </xsd:restriction>
  </xsd:simpleType>
  
  <!--
  Durations for valid and recheck time can be specified in the following way:

    y - years
    m - months
    w - weeks
    d - days
    H - hours
    M - minutes
    S - seconds

  while each of these is optional. Therefore, an example representing 1 week,
  3 days and 25 minutes would result in 1w3d25m.
   -->
  <xsd:simpleType name="durationType">
    <xsd:restriction base="xsd:string">
      <xsd:pattern value="([\d]+y)?([\d]+m)?([\d]+w)?([\d]+d)?([\d]+H)?([\d]+M)?([\d]+S)?" />
    </xsd:restriction>
  </xsd:simpleType>
  
  <!-- 
  Type definition for use attributes in include elements. These includes can
  either be included for the renderer or the editor only or both.
   -->
  <xsd:simpleType name="useType">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="renderer"/>
      <xsd:enumeration value="editor"/>
      <xsd:enumeration value="all"/>
    </xsd:restriction>
  </xsd:simpleType>
  
</xsd:schema>

=== digitalcafe/weblounge/modules/weblounge-common/src/test/resources/module.xml
<?xml version="1.0" encoding="UTF-8"?>
<module id="testmodule" xmlns="http://www.entwinemedia.com/weblounge/3.0/module" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.entwinemedia.com/weblounge/3.0/module http://www.entwinemedia.com/xsd/weblounge/3.0/module.xsd">
  <enable>true</enable>
  <name><![CDATA[Test module]]></name>
  <pagelets>
    <pagelet id="renderer" composeable="true">
      <name><![CDATA[Pagelet renderer]]></name>
      <renderer>file://renderer/renderer.jsp</renderer>
      <editor>file://renderer/editor.jsp</editor>
      <recheck>1d10M</recheck>
      <valid>1w1d1H1M</valid>
      <includes>
        <link use="renderer" href="http://localhost/css/stylesheet.css" type="text/css"></link>
      </includes>
    </pagelet>
  </pagelets>
  <actions>
    <action id="myaction">
      <name><![CDATA[Test]]></name>
      <class>ch.entwine.weblounge.common.impl.site.TestAction</class>
      <mountpoint>/test/</mountpoint>
      <page>/testpage/</page>
      <template>testtemplate</template>
      <recheck>0</recheck>
      <valid>1M</valid>
      <includes>
        <link href="http://localhost/css/stylesheet.css" type="text/css"></link>
        <script src="http://localhost/scripts/script.js" type="javascript"></script>
      </includes>
      <options>
        <option>
          <name>key</name>
          <value><![CDATA[value]]></value>
        </option>
      </options>
    </action>
  </actions>
  <jobs>
    <job id="testjob">
      <name><![CDATA[Job title]]></name>
      <class>ch.entwine.weblounge.common.impl.scheduler.TestJob</class>
      <schedule>0 0 * * 1</schedule>
      <options>
        <option>
          <name>key</name>
          <value><![CDATA[value]]></value>
        </option>
      </options>
    </job>
  </jobs>
  <imagestyles>
    <imagestyle id="modulestyle" composeable="true" preview="false">
      <name><![CDATA[Module image]]></name>
      <scalingmode>box</scalingmode>
      <width>150</width>
      <height>200</height>
    </imagestyle>
  </imagestyles>
  <options>
    <option>
      <name>complex</name>
      <value><![CDATA[complex]]></value>
      <value><![CDATA[value]]></value>
    </option>
    <option>
      <name>simple</name>
      <value><![CDATA[simple value]]></value>
    </option>
  </options>
</module>

=== digitalcafe/weblounge/modules/weblounge-test/src/main/resources/site/modules/test/module.xml
<module id="test" xmlns="http://www.entwinemedia.com/weblounge/3.0/module"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.entwinemedia.com/weblounge/3.0/module http://www.entwinemedia.com/xsd/weblounge/3.0/module.xsd">

  <enable>true</enable>
  <name>Testmodule</name>

  <pagelets>
    <pagelet id="content" composeable="false">
      <name>Page content showcase</name>
      <renderer>file://${module.root}/pagelets/content.jsp</renderer>
      <recheck>1d10M</recheck>
      <valid>1w1d1H1M</valid>
      <includes>
        <link href="file://${module.root}/css/greeting.css" rel="stylesheet"
          type="text/css" />
        <script src="file://${module.root}/scripts/greeting.js"
          type="text/javascript" />
      </includes>
    </pagelet>
    <pagelet id="include" composeable="false">
      <name>Pagelet includes showcase</name>
      <renderer>file://${module.root}/pagelets/include.jsp</renderer>
      <recheck>1d10M</recheck>
      <valid>1w1d1H1M</valid>
      <includes>
        <link href="file://${module.root}/css/greeting.css" rel="stylesheet"
          type="text/css" />
      </includes>
    </pagelet>
    <pagelet id="i18n" composeable="false">
      <name>I18n internationalization showcase</name>
      <renderer>file://${module.root}/pagelets/i18n.jsp</renderer>
    </pagelet>
    <pagelet id="nested" composeable="false">
      <name>Nested property tags showcase</name>
      <renderer>file://${module.root}/pagelets/nested.jsp</renderer>
    </pagelet>
    <pagelet id="editing" composeable="false">
      <name>Page editing showcase</name>
      <renderer>file://${module.root}/pagelets/editing.jsp</renderer>
      <editor>file://${module.root}/pagelets/editing_editor.jsp</editor>
    </pagelet>
    <pagelet id="modificationdate" composeable="true">
      <name>Modification date</name>
      <renderer>file://${module.root}/pagelets/modificationdate.jsp</renderer>
    </pagelet>
  </pagelets>

  <actions>
    <action id="greeter.html">
      <name>Greetings</name>
      <class>ch.entwine.weblounge.test.site.GreeterHTMLAction</class>
      <mountpoint>/greeting</mountpoint>
      <includes>
        <script src="file://${module.root}/scripts/greeting.js"
          type="text/javascript" />
      </includes>
    </action>
    <action id="greeter.html-targeted">
      <name>Greetings</name>
      <class>ch.entwine.weblounge.test.site.GreeterHTMLAction</class>
      <mountpoint>/greeting-targeted</mountpoint>
      <page>/test/htmlaction</page>
      <includes>
        <script src="file://${module.root}/scripts/greeting.js"
          type="text/javascript" />
      </includes>
    </action>
    <action id="greeter.html-templated">
      <name>Greetings</name>
      <class>ch.entwine.weblounge.test.site.GreeterHTMLAction</class>
      <mountpoint>/greeting-templated</mountpoint>
      <template>alternate</template>
      <includes>
        <script src="file://${module.root}/scripts/greeting.js"
          type="text/javascript" />
      </includes>
    </action>
    <action id="greeter.xml">
      <name>XML Greetings</name>
      <class>ch.entwine.weblounge.test.site.GreeterXMLAction</class>
      <mountpoint>/greeting/xml</mountpoint>
    </action>
    <action id="greeter.json">
      <name>JSON Greetings</name>
      <class>ch.entwine.weblounge.test.site.GreeterJSONAction</class>
      <mountpoint>/greeting/json</mountpoint>
    </action>
  </actions>

  <jobs>
    <job id="startup">
      <name>Job title</name>
      <class>ch.entwine.weblounge.test.site.SiteStartupJob</class>
      <schedule>@restart</schedule>
    </job>
    <job id="greeter">
      <name>Job title</name>
      <class>ch.entwine.weblounge.test.site.GreeterJob</class>
      <schedule>*/10 * * * *</schedule>
    </job>
    <!-- UNCOMMENT TO ACTIVATE <job id="mailpublisher"> <name>Mail Aggregator</name> 
      <class>ch.entwine.weblounge.bridge.mail.MailAggregator</class> <schedule>* 
      * * * *</schedule> <options> <option> <name>provider</name> <value>pop3</value> 
      </option> <option> <name>host</name> <value>mail.digitalcafe.ch</value> </option> 
      <option> <name>login</name> <value>weblounge</value> </option> <option> <name>password</name> 
      <value>test</value> </option> </options> </job> -->
  </jobs>

  <imagestyles>
    <imagestyle id="none">
      <name>Original size</name>
      <scalingmode>none</scalingmode>
    </imagestyle>
    <imagestyle id="box">
      <name>Scale to bounding box</name>
      <scalingmode>box</scalingmode>
      <width>250</width>
      <height>250</height>
    </imagestyle>
    <imagestyle id="cover">
      <name>Scale to cover area</name>
      <scalingmode>cover</scalingmode>
      <width>250</width>
      <height>250</height>
    </imagestyle>
    <imagestyle id="fill">
      <name>Scale to fill area and crop</name>
      <scalingmode>fill</scalingmode>
      <width>250</width>
      <height>250</height>
    </imagestyle>
    <imagestyle id="width">
      <name>Scale to fit width</name>
      <scalingmode>width</scalingmode>
      <width>250</width>
    </imagestyle>
    <imagestyle id="height">
      <name>Scale to fit height</name>
      <scalingmode>height</scalingmode>
      <height>250</height>
    </imagestyle>
  </imagestyles>

</module>

=== digitalcafe/weblounge/modules/weblounge-test/src/main/resources/site/modules/repository/module.xml
<?xml version="1.0" encoding="UTF-8"?>
<module id="repository" xmlns="http://www.entwinemedia.com/weblounge/3.0/module" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.entwinemedia.com/weblounge/3.0/module http://www.entwinemedia.com/xsd/weblounge/3.0/module.xsd">
  
  <enable>true</enable>
  <name>Media</name>
  
  <pagelets>
    <pagelet id="download" composeable="true">
      <name>Download</name>
      <renderer>file://${module.root}/jsp/download/download.jsp</renderer>
      <editor>file://${module.root}/jsp/download/download_editor.jsp</editor>
      <includes>
        <link use="editor" href="file://${module.root}/jsp/download/download.css" rel="stylesheet" type="text/css"></link>
        <script use="editor" src="file://${module.root}/jsp/download/download.js" type="text/javascript"></script>
      </includes>
    </pagelet>
    
    <pagelet id="image" composeable="true">
      <name>Image</name>
      <renderer>file://${module.root}/jsp/image/image.jsp</renderer>
      <renderer type="feed">file://${module.root}/jsp/image/image.jsp</renderer>
      <editor>file://${module.root}/jsp/image/image_editor.jsp</editor>
      <includes>
        <link use="renderer" href="file://${module.root}/jsp/image/apple_overlay.css" rel="stylesheet" type="text/css"></link>
        <link use="editor" href="file://${module.root}/jsp/image/image.css" rel="stylesheet" type="text/css"></link>
        <script jquery="1.6" use="renderer" src="file://${module.root}/jsp/image/apple_overlay.js" type="text/javascript"></script>
        <script use="editor" src="file://${module.root}/jsp/image/image.js" type="text/javascript"></script>
      </includes>
    </pagelet>
    
    <pagelet id="gallery" composeable="true">
      <name>Image gallery</name>
      <renderer>file://${module.root}/jsp/gallery/gallery.jsp</renderer>
      <editor>file://${module.root}/jsp/gallery/gallery_editor.jsp</editor>
      <includes>
        <link use="editor" href="file://${module.root}/jsp/gallery/gallery.css" rel="stylesheet" type="text/css"></link>
        <script use="editor" src="file://${module.root}/jsp/gallery/gallery.js" type="text/javascript"></script>
        <script use="renderer" src="file://${module.root}/js/galleria/galleria-1.2.5.min.js" type="text/javascript"></script>
      </includes>
    </pagelet>
  </pagelets>
  
  <imagestyles>
    <imagestyle id="editorpreview" composeable="true" preview="true">
      <name><![CDATA[Editor Preview]]></name>
      <scalingmode>cover</scalingmode>
      <width>200</width>
      <height>150</height>
    </imagestyle>
  </imagestyles>
  
</module>
