=== digitalcafe/weblounge/modules/weblounge-common/src/main/resources/xsd/site.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
  targetNamespace="http://www.entwinemedia.com/weblounge/3.0/site"
  xmlns="http://www.entwinemedia.com/weblounge/3.0/site"
  elementFormDefault="qualified">

  <xsd:element name="site">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="autostart" type="xsd:boolean" />
        <xsd:element name="class" type="xsd:string" minOccurs="0" />
        <xsd:element name="name" type="xsd:string" minOccurs="0" />
        <xsd:element ref="languages" />
        <xsd:element ref="domains" />
        <xsd:element ref="security" />
        <xsd:element ref="templates" minOccurs="0" />
        <xsd:element ref="options" minOccurs="0" />
      </xsd:sequence>
      <xsd:attribute name="id" type="idType" use="required" />
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="security">
    <xsd:complexType>
      <xsd:all>
        <xsd:element name="configuration" type="xsd:anyURI" minOccurs="0" />
        <xsd:element name="digest" type="digestType" minOccurs="0" />
        <xsd:element ref="administrator" />
        <xsd:element ref="roles" minOccurs="0" maxOccurs="1" />
      </xsd:all>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="administrator">
    <xsd:complexType>
      <xsd:all>
        <xsd:element name="login" type="xsd:string" />
        <xsd:element ref="password" />
        <xsd:element name="name" type="xsd:string" />
        <xsd:element ref="email" minOccurs="0" maxOccurs="1" />
      </xsd:all>
    </xsd:complexType>
  </xsd:element>

  <xsd:simpleType name="digestType">
     <xsd:restriction base="xsd:string">
       <xsd:enumeration value="plain" />
       <xsd:enumeration value="md5" />
     </xsd:restriction>
  </xsd:simpleType>

  <xsd:element name="password">
    <xsd:complexType>
      <xsd:simpleContent>
        <xsd:extension base="xsd:string">
          <xsd:attribute name="type" use="required" type="digestType"/>
        </xsd:extension>
      </xsd:simpleContent>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="email">
    <xsd:simpleType>
      <xsd:restriction base="xsd:string">
        <xsd:pattern value="" />
      </xsd:restriction>
    </xsd:simpleType>
  </xsd:element>

  <xsd:element name="roles">
    <xsd:complexType>
      <xsd:all>
        <xsd:element name="administrator" type="xsd:string" minOccurs="0" maxOccurs="1"/>
        <xsd:element name="publisher" type="xsd:string" minOccurs="0" maxOccurs="1" />
        <xsd:element name="editor" type="xsd:string" minOccurs="0" maxOccurs="1" />
        <xsd:element name="guest" type="xsd:string" minOccurs="0" maxOccurs="1" />
      </xsd:all>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="domains">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="url" maxOccurs="unbounded" />
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="url">
    <xsd:complexType>
      <xsd:simpleContent>
        <xsd:extension base="xsd:string">
          <xsd:attribute name="default" type="xsd:boolean" />
          <xsd:attribute name="environment" type="environmentType" />
        </xsd:extension>
      </xsd:simpleContent>
    </xsd:complexType>
  </xsd:element>

  <xsd:simpleType name="environmentType">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="production" />
      <xsd:enumeration value="staging" />
      <xsd:enumeration value="development" />
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:element name="templates">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="template" maxOccurs="unbounded"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="template">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="name" type="xsd:string" minOccurs="0" />
        <xsd:element name="renderer" type="xsd:anyURI" minOccurs="0" />
        <xsd:element name="stage" type="xsd:string" minOccurs="0" />
        <xsd:element name="recheck" type="durationType" minOccurs="0" />
        <xsd:element name="valid" type="durationType" minOccurs="0" />
        <xsd:element ref="includes" minOccurs="0"/>
      </xsd:sequence>
      <xsd:attribute name="id" type="xsd:ID" />
      <xsd:attribute name="composeable" type="xsd:boolean" />
      <xsd:attribute name="default" type="xsd:boolean" />
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="languages">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="language" maxOccurs="unbounded" />
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="language">
    <xsd:complexType>
      <xsd:simpleContent>
        <xsd:extension base="xsd:language">
          <xsd:attribute name="default" type="xsd:boolean" />
        </xsd:extension>
      </xsd:simpleContent>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="options">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="option" maxOccurs="unbounded" />
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

  <!--
  Options are defined by a name and either a single value or a list of values.
  Multiple values are put into a value element each.
  -->
  <xsd:element name="option">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="name" type="xsd:string" minOccurs="1" maxOccurs="1" />
        <xsd:element name="value" type="optionValueType" minOccurs="1" maxOccurs="unbounded" />
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  
  <xsd:complexType name="optionValueType">
    <xsd:simpleContent>
      <xsd:extension base="xsd:string">
        <xsd:attribute name="environment" type="environmentType" />
      </xsd:extension>
    </xsd:simpleContent>
  </xsd:complexType>

  <xsd:element name="includes">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="link" minOccurs="0" maxOccurs="unbounded" />
        <xsd:element ref="script" minOccurs="0" maxOccurs="unbounded" />
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="link">
    <xsd:complexType>
      <xsd:attribute name="use" type="useType" use="optional" />
      <xsd:attribute name="href" type="xsd:anyURI" use="required" />
      <xsd:attribute name="type" type="xsd:string" use="required" />
      <xsd:attribute name="charset" type="xsd:string" use="optional" />
      <xsd:attribute name="media" type="xsd:string" use="optional" />
      <xsd:attribute name="rel" type="xsd:string" use="optional" />
      <xsd:attribute name="rev" type="xsd:string" use="optional" />
    </xsd:complexType>
  </xsd:element>
  
  <xsd:element name="script">
    <xsd:complexType>
      <xsd:attribute name="jquery" type="xsd:string" use="optional" />
      <xsd:attribute name="use" type="useType" use="optional" />
      <xsd:attribute name="src" type="xsd:anyURI" use="required" />
      <xsd:attribute name="type" type="xsd:string" use="required" />
      <xsd:attribute name="charset" type="xsd:string" use="optional" />
      <xsd:attribute name="defer" type="xsd:boolean" use="optional" />
    </xsd:complexType>
  </xsd:element>

  <!-- 
  Type definition for identifiers. Since identifiers are used in path names
  and potentially database table and column names as well, they are restricted
  to contain commonly unproblematic characters only.
   -->
  <xsd:simpleType name="idType">
    <xsd:restriction base="xsd:ID">
      <xsd:pattern value="[a-zA-Z0-9]+[a-zA-Z0-9\-_.]*" />
    </xsd:restriction>
  </xsd:simpleType>

  <!--
  Durations for valid and recheck time can be specified in the following way:

    y - years
    m - months
    w - weeks
    d - days
    H - hours
    M - minutes
    S - seconds

  while each of these is optional. Therefore, an example representing 1 week,
  3 days and 25 minutes would result in 1w3d25m.
   -->
  <xsd:simpleType name="durationType">
    <xsd:restriction base="xsd:string">
      <xsd:pattern value="([\d]+y)?([\d]+m)?([\d]+w)?([\d]+d)?([\d]+H)?([\d]+M)?([\d]+S)?" />
    </xsd:restriction>
  </xsd:simpleType>

  <!-- 
  Type definition for use attributes in include elements. These includes can
  either be included for the renderer or the editor only or both.
   -->
  <xsd:simpleType name="useType">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="renderer"/>
      <xsd:enumeration value="editor"/>
      <xsd:enumeration value="all"/>
    </xsd:restriction>
  </xsd:simpleType>

</xsd:schema>

=== digitalcafe/weblounge/modules/weblounge-common/src/test/resources/site.xml
<?xml version="1.0" encoding="UTF-8"?>
<site id="dev" xmlns="http://www.entwinemedia.com/weblounge/3.0/site" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.entwinemedia.com/weblounge/3.0/site http://www.entwinemedia.com/xsd/weblounge/3.0/site.xsd">
  <autostart>true</autostart>
  <name><![CDATA[Main site]]></name>
  <languages>
    <language default="true">de</language>
    <language>en</language>
  </languages>
  <domains>
  	<url default="true" environment="production">http://www.weblounge.org</url>
  	<url environment="staging">http://*.nowhere.com</url>
    <url environment="development">http://localhost:8080</url>
  </domains>
  <security>
    <configuration>file://security.xml</configuration>
    <digest>md5</digest>
    <administrator>
      <login>blogadmin</login>
      <password type="plain"><![CDATA[secret]]></password>
      <name><![CDATA[Web Office]]></name>
      <email>weboffice@nowhere.com</email>
    </administrator>
    <roles>
	  <administrator>my-admin</administrator>
	  <publisher>my-publisher</publisher>
	  <editor>my-editor</editor>
	  <guest>my-guest</guest>
    </roles>
  </security>
  <templates>
    <template id="default" composeable="true" default="true">
      <name><![CDATA[Default template]]></name>
      <renderer>file://template/default.jsp</renderer>
      <stage>boxes</stage>
      <recheck>1d10M</recheck>
      <valid>1w1d1H1M</valid>
    </template>
    <template id="mobile" composeable="true">
      <name><![CDATA[Mobile]]></name>
      <renderer>file://template/mobile.jsp</renderer>
      <recheck>1H</recheck>
      <valid>1w</valid>
    </template>
  </templates>
  <options>
    <option>
    	<name>env.specific</name>
      <value environment="development"><![CDATA[development]]></value>
    </option>
    <option>
      <name>media.url</name>
      <value><![CDATA[http://media.swissunihockey.ch/dev]]></value>
    </option>
  </options>
</site>

=== digitalcafe/weblounge/modules/weblounge-test/src/main/resources/site/site.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<site id="weblounge-test" xmlns="http://www.entwinemedia.com/weblounge/3.0/site" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.entwinemedia.com/weblounge/3.0/site http://www.entwinemedia.com/xsd/weblounge/3.0/site.xsd">
  <autostart>true</autostart>
  <class>ch.entwine.weblounge.test.site.TestSite</class>
  <name>Weblounge Test Site</name>
  <languages>
    <language default="true">de</language>
    <language>fr</language>
    <language>en</language>
  </languages>
  <domains>
    <url environment="production" default="true">http://test:8080</url>
    <url environment="production">http://localhost:8080</url>
    <url environment="production">http://127.0.0.1:8080</url>
    <url environment="staging" default="true">http://127.0.0.1:8080</url>
    <url environment="staging">http://localhost:8080</url>
    <url environment="staging">http://test:8080</url>
    <url environment="development" default="true">http://localhost:8080</url>
    <url environment="development">http://127.0.0.1:8080</url>
    <url environment="development">http://test:8080</url>
  </domains>
  <security>
    <digest>md5</digest>
    <administrator>
      <login>testadmin</login>
      <password type="plain">secret</password>
      <name>Web Office</name>
      <email>weboffice@nowhere.com</email>
    </administrator>
  </security>
  <templates>
    <template id="default" composeable="true" default="true">
      <name>Default template</name>
      <renderer>file://${site.root}/templates/default.jsp</renderer>
      <stage>main</stage>
      <recheck>1d10M</recheck>
      <valid>1w1d1H1M</valid>
    </template>
    <template id="alternate" composeable="true">
      <name>Default template</name>
      <renderer>file://${site.root}/templates/alternate.jsp</renderer>
      <stage>main</stage>
    </template>
    <template id="ghost" composeable="false">
      <name>Ghost template</name>
      <renderer>file://${site.root}/templates/ghost.jsp</renderer>
      <stage>main</stage>
    </template>
    <template id="welcome" composeable="false">
      <name>Welcome page</name>
      <renderer>file://${site.root}/templates/welcome.jsp</renderer>
      <stage>main</stage>
      <recheck>1d10M</recheck>
      <valid>1w1d1H1M</valid>
    </template>
    <template id="search" composeable="false">
      <name>Search template</name>
      <renderer>file://${site.root}/templates/search.jsp</renderer>
      <stage>main</stage>
      <recheck>10M</recheck>
      <valid>1H</valid>
    </template>
  </templates>
  <options>
  	<option>
  		<name>contentrepository.type</name>
  		<value>ch.entwine.weblounge.contentrepository.impl.bundle.WritableBundleContentRepository</value>
  	</option>
  </options>
</site>
