=== digitalcafe/weblounge/modules/weblounge-common/src/main/resources/xsd/test.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.entwinemedia.com/weblounge/3.0/test" xmlns="http://www.entwinemedia.com/weblounge/3.0/test"
	elementFormDefault="qualified">

  <xsd:element name="test">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="name" type="xsd:string" minOccurs="0" />
        <xsd:element ref="test-case" minOccurs="0" maxOccurs="unbounded" />
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="test-case">
  	<xsd:complexType>
  	  <xsd:sequence>
        <xsd:element name="name" type="xsd:string" minOccurs="0" />
        <xsd:element ref="url" minOccurs="1"/>
        <xsd:element ref="parameter" minOccurs="0" maxOccurs="unbounded" />
        <xsd:element ref="assertions" minOccurs="1" />
      </xsd:sequence>
  	</xsd:complexType>
  </xsd:element>

  <xsd:element name="assertions">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="status" minOccurs="0" />
        <xsd:element ref="exists" minOccurs="0" maxOccurs="unbounded" />
        <xsd:element ref="not-exists" minOccurs="0" maxOccurs="unbounded" />
        <xsd:element ref="equals" minOccurs="0" maxOccurs="unbounded" />
        <xsd:element ref="not-equals" minOccurs="0" maxOccurs="unbounded" />
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="url">
    <xsd:complexType>
      <xsd:simpleContent>
        <xsd:extension base="xsd:anyURI">
          <xsd:attribute name="method" type="methodType" use="required" />
        </xsd:extension>
      </xsd:simpleContent>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="parameter">
    <xsd:complexType>
      <xsd:simpleContent>
        <xsd:extension base="xsd:string">
          <xsd:attribute name="name" type="xsd:string" use="required" />
        </xsd:extension>
      </xsd:simpleContent>
    </xsd:complexType>
  </xsd:element>
  
  <xsd:element name="status">
    <xsd:complexType>
      <xsd:simpleContent>
        <xsd:extension base="integerListType" />
      </xsd:simpleContent>
    </xsd:complexType>
  </xsd:element>
  
  <xsd:element name="exists">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="path" type="xsd:string" minOccurs="1" />
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="not-exists">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="path" type="xsd:string" minOccurs="1" />
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="equals">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="path" type="xsd:string" minOccurs="1" />
        <xsd:element name="value" type="xsd:string" minOccurs="1" />
      </xsd:sequence>
      <xsd:attribute name="ignorewhitespace" type="xsd:boolean" />
      <xsd:attribute name="ignorecase" type="xsd:boolean" />
      <xsd:attribute name="regularexpression" type="xsd:boolean" />
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="not-equals">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="path" type="xsd:string" minOccurs="1" />
        <xsd:element name="value" type="xsd:string" minOccurs="1" />
      </xsd:sequence>
      <xsd:attribute name="ignorewhitespace" type="xsd:boolean" />
      <xsd:attribute name="ignorecase" type="xsd:boolean" />
      <xsd:attribute name="regularexpression" type="xsd:boolean" />
    </xsd:complexType>
  </xsd:element>
  
  <!-- Type definition for a list of integers separated by whitespace -->
  <xsd:simpleType name="integerListType">
    <xsd:list itemType="xsd:integer"/>
  </xsd:simpleType>
    
  <!-- 
  Type definition for method attributes in url elements.
  -->
  <xsd:simpleType name="methodType">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="options"/>
      <xsd:enumeration value="post"/>
      <xsd:enumeration value="head"/>
      <xsd:enumeration value="get"/>
      <xsd:enumeration value="post"/>
      <xsd:enumeration value="put"/>
      <xsd:enumeration value="delete"/>
    </xsd:restriction>
  </xsd:simpleType>
  
</xsd:schema>

=== digitalcafe/weblounge/modules/weblounge-test/src/main/resources/site/tests/home.xml
<test xmlns="http://www.entwinemedia.com/weblounge/3.0/test" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.entwinemedia.com/weblounge/3.0/test http://www.entwinemedia.com/xsd/weblounge/3.0/test.xsd">
  <name>Homepage Tests</name>
  <test-case>
    <name>Page title</name>
    <url method="get">/</url>
    <assertions>
      <status>200 304</status>
      <equals ignorewhitespace="true" ignorecase="false">
        <path>/html/body/h1</path>
        <value>Welcome to the Weblounge 3.0 testpage!</value>
      </equals>
    </assertions>
  </test-case>
</test>

=== digitalcafe/weblounge/modules/weblounge-common/src/test/resources/integrationtest.xml
<test xmlns="http://www.entwinemedia.com/weblounge/3.0/test" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.entwinemedia.com/weblounge/3.0/test http://www.entwinemedia.com/xsd/weblounge/3.0/test.xsd">
  <name><![CDATA[Action Tests]]></name>
  <test-case>
    <name><![CDATA[English greeting test]]></name>
    <url method="get">/greeting</url>
    <parameter name="language">english</parameter>
    <assertions>
      <status>200 304</status>
      <exists>
        <path>//div[@id='main']/h1</path>
      </exists>
      <not-exists>
        <path>//div[@id='main']/h2</path>
      </not-exists>
      <equals ignorewhitespace="true" ignorecase="true">
        <path>//div[@id='main']/h1</path>
        <value><![CDATA[hello world i am happy today]]></value>
      </equals>
      <equals regularexpression="true">
        <path>//div[@id='main']/h2</path>
        <value><![CDATA[^hello world i am [\w]* now$]]></value>
      </equals>
      <not-equals ignorewhitespace="true" ignorecase="false">
        <path>//div[@id='main']/h2</path>
        <value><![CDATA[hello world i am happy now]]></value>
      </not-equals>
    </assertions>
  </test-case>
  <test-case>
    <name><![CDATA[German greeting test]]></name>
    <url method="get">/greeting</url>
    <parameter name="language">german</parameter>
    <assertions>
      <status>200 304</status>
      <exists>
        <path>//div[@id='main']/h1</path>
      </exists>
      <not-exists>
        <path>//div[@id='main']/h2</path>
      </not-exists>
      <equals ignorewhitespace="true" ignorecase="true">
        <path>//div[@id='main']/h1</path>
        <value><![CDATA[hello world i am happy today]]></value>
      </equals>
      <not-equals ignorewhitespace="true" ignorecase="false">
        <path>//div[@id='main']/h1</path>
        <value><![CDATA[hello world i am happy today]]></value>
      </not-equals>
    </assertions>
  </test-case>
</test>

=== digitalcafe/weblounge/modules/weblounge-test/src/main/resources/site/modules/test/tests/greetings.xml
<test xmlns="http://www.entwinemedia.com/weblounge/3.0/test" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.entwinemedia.com/weblounge/3.0/test http://www.entwinemedia.com/xsd/weblounge/3.0/test.xsd">
  <name>Greeting Action Tests</name>
  <test-case>
    <name>English greeting test</name>
    <url method="get">/greeting</url>
    <parameter name="language">english</parameter>
    <assertions>
      <status>200 304</status>
      <exists>
        <path>//div[@id='main']/h1</path>
      </exists>
      <not-exists>
        <path>//div[@id='main']/h2</path>
      </not-exists>
      <equals ignorewhitespace="false" ignorecase="false">
        <path>//div[@id='greeting']</path>
        <value>&#1605;&#1585;&#1581;&#1576;&#1575; &#1571;&#1606;&#1575; &#1571;&#1588;&#1593;&#1585; &#1576;&#1575;&#1604;&#1587;&#1593;&#1575;&#1583;&#1577; &#1575;&#1604;&#1593;&#1575;&#1604;&#1605; &#1575;&#1604;&#1610;&#1608;&#1605;</value>
      </equals>
      <not-equals ignorewhitespace="true" ignorecase="false">
        <path>//div[@id='greeting']</path>
        <value>hello world i am happy today</value>
      </not-equals>
    </assertions>
  </test-case>
</test>
